Day7/urls.py
from django.contrib import admin
from django.urls import path,include
import app1
import app2
from app1 import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home_project,name='home'),
    path('app1/',include("app1.urls")),
    path('',include("app2.urls")),

]

app1/urls.py
from django.urls import path
from app1 import views
app_name="app1"
urlpatterns = [
    path("home/",views.home,name="home_app1"),
]

app2/urls.py
from django.urls import path
from app2 import views
app_name="app2"
urlpatterns = [
    path("home/",views.home,name="home_app2"),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,'home.html')

def home_project(request):
    return render(request,'home_project.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,'home_app2.html')

app1/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>APP1 Home</title>
    <link rel="stylesheet" href="{% static 'css/style_app1.css' %}">
</head>
<body>
    <h1>welcome to app1 home</h1>
    <img src="{% static 'images/image_app1.jpg' %}" alt="image not found">
    <a href="{% url 'home' %}">click here to go for project home</a>
</body>
</html>

app2/templates/home_app2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>APP2 Home</title>
    <link rel="stylesheet" href="{% static 'css/style_app2.css' %}">
</head>
<body>
    <h1>welcome to app2 home</h1>
    <img src="{% static 'images/image_app2.jpg' %}" alt="image not found">
    <a href="{% url 'home' %}">click here to go for project home</a>
</body>
</html>

templates/home_project.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>APP2 Home</title>
    <link rel="stylesheet" href="{% static 'css/style_app2.css' %}">
</head>
<body>
    <h1>welcome to home</h1>
    <a href="{% url 'app1:home_app1' %}">click here to go for app1 home</a><br>
    <a href="{% url 'app2:home_app2' %}">click here to go for app2 home</a><br>
</body>
</html>